use super::storage::store::Store;
use crate::string_enum;
use std::sync::Arc;

string_enum! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum ComdType {
        default = Exec;
        Exec => "EXEC",

        PING => "PING",
        ECHO => "ECHO",
        INFO => "INFO",
        FLUSH => "FLUSH",
        DBSIZE => "DBSIZE",
        TYPE => "TYPE",
        BGSAVE => "BGSAVE",
        SAVE => "SAVE",
        LASTSAVE => "LASTSAVE",
        TIME => "TIME",
        COMMAND => "COMMAND",
        CLUSTER => "CLUSTER",
        QUIT => "QUIT",
        HELLO => "HELLO",
        SELECT => "SELECT",
        FLUSHALL => "FLUSHALL",
        FLUSHDB => "FLUSHDB",
        AUTH => "AUTH",
        RESET => "RESET",
        CLIENT => "CLIENT",
        CONFIG => "CONFIG",
        SLOWLOG => "SLOWLOG",
        ACL => "ACL",
        OBJECT => "OBJECT",
        SORT => "SORT",

        GET => "GET",
        SET => "SET",
        SETNX => "SETNX",
        SETEX => "SETEX",
        PSETEX => "PSETEX",
        GETDEL => "GETDEL",
        GETSET => "GETSET",
        GETEX => "GETEX",
        MSET => "MSET",
        MSETNX => "MSETNX",
        MGET => "MGET",
        INCR => "INCR",
        DECR => "DECR",
        INCRBY => "INCRBY",
        DECRBY => "DECRBY",
        INCRBYFLOAT => "INCRBYFLOAT",
        APPEND => "APPEND",
        STRLEN => "STRLEN",
        GETRANGE => "GETRANGE",
        SETRANGE => "SETRANGE",
        SUBSTR => "SUBSTR",
        LCS => "LCS",

        DEL => "DEL",
        UNLINK => "UNLINK",
        EXISTS => "EXISTS",
        TTL => "TTL",
        PTTL => "PTTL",
        EXPIRE => "EXPIRE",
        PEXPIRE => "PEXPIRE",
        EXPIREAT => "EXPIREAT",
        EXPIRETIME => "EXPIRETIME",
        PEXPIRETIME => "PEXPIRETIME",
        PERSIST => "PERSIST",
        RENAME => "RENAME",
        RENAMENX => "RENAMENX",
        COPY => "COPY",
        RANDOMKEY => "RANDOMKEY",
        KEYS => "KEYS",
        SCAN => "SCAN",
        TOUCH => "TOUCH",

        HSET => "HSET",
        HSETNX => "HSETNX",
        HGET => "HGET",
        HMGET => "HMGET",
        HMSET => "HMSET",
        HGETALL => "HGETALL",
        HDEL => "HDEL",
        HEXISTS => "HEXISTS",
        HLEN => "HLEN",
        HKEYS => "HKEYS",
        HVALS => "HVALS",
        HINCRBY => "HINCRBY",
        HINCRBYFLOAT => "HINCRBYFLOAT",
        HRANDFIELD => "HRANDFIELD",
        HSCAN => "HSCAN",

        LPUSH => "LPUSH",
        RPUSH => "RPUSH",
        LPOP => "LPOP",
        RPOP => "RPOP",
        LLEN => "LLEN",
        LINDEX => "LINDEX",
        LSET => "LSET",
        LRANGE => "LRANGE",
        LTRIM => "LTRIM",
        LREM => "LREM",
        LINSERT => "LINSERT",
        LPOS => "LPOS",
        LMOVE => "LMOVE",
        RPOPLPUSH => "RPOPLPUSH",
        BLPOP => "BLPOP",
        BRPOP => "BRPOP",
        BLMOVE => "BLMOVE",

        SADD => "SADD",
        SREM => "SREM",
        SISMEMBER => "SISMEMBER",
        SMISMEMBER => "SMISMEMBER",
        SMEMBERS => "SMEMBERS",
        SCARD => "SCARD",
        SPOP => "SPOP",
        SRANDMEMBER => "SRANDMEMBER",
        SMOVE => "SMOVE",
        SUNION => "SUNION",
        SINTER => "SINTER",
        SDIFF => "SDIFF",
        SUNIONSTORE => "SUNIONSTORE",
        SINTERSTORE => "SINTERSTORE",
        SDIFFSTORE => "SDIFFSTORE",
        SINTERCARD => "SINTERCARD",
        SSCAN => "SSCAN",

        ZADD => "ZADD",
        ZREM => "ZREM",
        ZSCORE => "ZSCORE",
        ZMSCORE => "ZMSCORE",
        ZRANK => "ZRANK",
        ZREVRANK => "ZREVRANK",
        ZCARD => "ZCARD",
        ZCOUNT => "ZCOUNT",
        ZLEXCOUNT => "ZLEXCOUNT",
        ZINCRBY => "ZINCRBY",
        ZRANGE => "ZRANGE",
        ZREVRANGE => "ZREVRANGE",
        ZRANGEBYSCORE => "ZRANGEBYSCORE",
        ZREVRANGEBYSCORE => "ZREVRANGEBYSCORE",
        ZRANGEBYLEX => "ZRANGEBYLEX",
        ZRANGESTORE => "ZRANGESTORE",
        ZPOPMIN => "ZPOPMIN",
        ZPOPMAX => "ZPOPMAX",
        BZPOPMIN => "BZPOPMIN",
        BZPOPMAX => "BZPOPMAX",
        ZUNION => "ZUNION",
        ZINTER => "ZINTER",
        ZDIFF => "ZDIFF",
        ZUNIONSTORE => "ZUNIONSTORE",
        ZINTERSTORE => "ZINTERSTORE",
        ZDIFFSTORE => "ZDIFFSTORE",
        ZRANDMEMBER => "ZRANDMEMBER",
        ZSCAN => "ZSCAN",

        SETBIT => "SETBIT",
        GETBIT => "GETBIT",
        BITCOUNT => "BITCOUNT",
        BITPOS => "BITPOS",
        BITOP => "BITOP",
        BITFIELD => "BITFIELD",

        PFADD => "PFADD",
        PFCOUNT => "PFCOUNT",
        PFMERGE => "PFMERGE",

        JSONSET => "JSON.SET",
        JSONGET => "JSON.GET",
        JSONDEL => "JSON.DEL",
        JSONFORGET => "JSON.FORGET",
        JSONTYPE => "JSON.TYPE",
        JSONNUMINCRBY => "JSON.NUMINCRBY",
        JSONNUMMULTBY => "JSON.NUMMULTBY",
        JSONSTRAPPEND => "JSON.STRAPPEND",
        JSONSTRLEN => "JSON.STRLEN",
        JSONARRAPPEND => "JSON.ARRAPPEND",
        JSONARRINDEX => "JSON.ARRINDEX",
        JSONARRINSERT => "JSON.ARRINSERT",
        JSONARRLEN => "JSON.ARRLEN",
        JSONARRPOP => "JSON.ARRPOP",
        JSONARRTRIM => "JSON.ARRTRIM",
        JSONOBJKEYS => "JSON.OBJKEYS",
        JSONOBJLEN => "JSON.OBJLEN",
        JSONTOGGLE => "JSON.TOGGLE",
        JSONCLEAR => "JSON.CLEAR",
        JSONMGET => "JSON.MGET",
        JSONRESP => "JSON.RESP",

        GEOADD => "GEOADD",
        GEOPOS => "GEOPOS",
        GEODIST => "GEODIST",
        GEOHASH => "GEOHASH",
        GEOSEARCH => "GEOSEARCH",
        GEOSEARCHSTORE => "GEOSEARCHSTORE",

        XADD => "XADD",
        XLEN => "XLEN",
        XRANGE => "XRANGE",
        XREVRANGE => "XREVRANGE",
        XREAD => "XREAD",
        XTRIM => "XTRIM",
        XDEL => "XDEL",
        XGROUP => "XGROUP",
        XACK => "XACK",
        XINFO => "XINFO",

        MULTI => "MULTI",
        DISCARD => "DISCARD",
        WATCH => "WATCH",
        UNWATCH => "UNWATCH",
    }
}

pub fn execute(parts: &[&str], store: &Arc<Store>, out: &mut Vec<u8>) {
    if parts.is_empty() {
        out.extend_from_slice(b"-ERR invalid command\r\n");
        return;
    }

    let cmd = ComdType::from(parts[0]);
    match cmd {
        ComdType::PING => connection::ping(parts, out),
        ComdType::ECHO => connection::echo(parts, out),
        ComdType::INFO => connection::info(store, out),
        ComdType::FLUSH => connection::flush(store, out),
        ComdType::DBSIZE => connection::dbsize(store, out),
        ComdType::TYPE => connection::type_of(parts, store, out),
        ComdType::BGSAVE => connection::bgsave(store, out),
        ComdType::SAVE => connection::save(store, out),
        ComdType::LASTSAVE => connection::lastsave(parts, out),
        ComdType::TIME => connection::time(parts, out),
        ComdType::COMMAND => connection::command_cmd(parts, out),
        ComdType::CLUSTER => connection::cluster_cmd(parts, store, out),
        ComdType::QUIT => connection::quit(out),
        ComdType::HELLO => connection::hello(parts, out),
        ComdType::SELECT => connection::select(parts, out),
        ComdType::FLUSHALL => connection::flushall(store, out),
        ComdType::FLUSHDB => connection::flushdb(store, out),
        ComdType::AUTH => connection::auth(parts, out),
        ComdType::RESET => connection::reset(out),
        ComdType::CLIENT => connection::client_cmd(parts, out),
        ComdType::CONFIG => connection::config_cmd(parts, out),
        ComdType::SLOWLOG => connection::slowlog_cmd(parts, out),
        ComdType::ACL => connection::acl_cmd(parts, out),
        ComdType::OBJECT => connection::object_cmd(parts, store, out),
        ComdType::SORT => connection::sort_cmd(parts, store, out),

        ComdType::GET => string::get(parts, store, out),
        ComdType::SET => string::set(parts, store, out),
        ComdType::SETNX => string::setnx(parts, store, out),
        ComdType::SETEX => string::setex(parts, store, out),
        ComdType::PSETEX => string::psetex(parts, store, out),
        ComdType::GETDEL => string::getdel(parts, store, out),
        ComdType::GETSET => string::getset(parts, store, out),
        ComdType::GETEX => string::getex(parts, store, out),
        ComdType::MSET => string::mset(parts, store, out),
        ComdType::MSETNX => string::msetnx(parts, store, out),
        ComdType::MGET => string::mget(parts, store, out),
        ComdType::INCR => string::incr(parts, store, out),
        ComdType::DECR => string::decr(parts, store, out),
        ComdType::INCRBY => string::incrby(parts, store, out),
        ComdType::DECRBY => string::decrby(parts, store, out),
        ComdType::INCRBYFLOAT => string::incrbyfloat(parts, store, out),
        ComdType::APPEND => string::append(parts, store, out),
        ComdType::STRLEN => string::strlen(parts, store, out),
        ComdType::GETRANGE => string::getrange(parts, store, out),
        ComdType::SETRANGE => string::setrange(parts, store, out),
        ComdType::SUBSTR => string::substr(parts, store, out),
        ComdType::LCS => string::lcs(parts, store, out),

        ComdType::DEL => keys::del(parts, store, out),
        ComdType::UNLINK => keys::unlink(parts, store, out),
        ComdType::EXISTS => keys::exists_check(parts, store, out),
        ComdType::TTL => keys::ttl_check(parts, store, out),
        ComdType::PTTL => keys::pttl_check(parts, store, out),
        ComdType::EXPIRE => keys::expire(parts, store, out),
        ComdType::PEXPIRE => keys::pexpire(parts, store, out),
        ComdType::EXPIREAT => keys::expireat(parts, store, out),
        ComdType::EXPIRETIME => keys::expiretime(parts, store, out),
        ComdType::PEXPIRETIME => keys::pexpiretime(parts, store, out),
        ComdType::PERSIST => keys::persist(parts, store, out),
        ComdType::RENAME => keys::rename(parts, store, out),
        ComdType::RENAMENX => keys::renamenx(parts, store, out),
        ComdType::COPY => keys::copy(parts, store, out),
        ComdType::RANDOMKEY => keys::randomkey(parts, store, out),
        ComdType::KEYS => keys::keys(parts, store, out),
        ComdType::SCAN => scan::scan(parts, store, out),
        ComdType::TOUCH => keys::touch(parts, store, out),

        ComdType::HSET => hash::hset(parts, store, out),
        ComdType::HSETNX => hash::hsetnx(parts, store, out),
        ComdType::HGET => hash::hget(parts, store, out),
        ComdType::HMGET => hash::hmget(parts, store, out),
        ComdType::HMSET => hash::hmset(parts, store, out),
        ComdType::HGETALL => hash::hgetall(parts, store, out),
        ComdType::HDEL => hash::hdel(parts, store, out),
        ComdType::HEXISTS => hash::hexists(parts, store, out),
        ComdType::HLEN => hash::hlen(parts, store, out),
        ComdType::HKEYS => hash::hkeys(parts, store, out),
        ComdType::HVALS => hash::hvals(parts, store, out),
        ComdType::HINCRBY => hash::hincrby(parts, store, out),
        ComdType::HINCRBYFLOAT => hash::hincrbyfloat(parts, store, out),
        ComdType::HRANDFIELD => hash::hrandfield(parts, store, out),
        ComdType::HSCAN => hash::hscan(parts, store, out),

        ComdType::LPUSH => list::lpush(parts, store, out),
        ComdType::RPUSH => list::rpush(parts, store, out),
        ComdType::LPOP => list::lpop(parts, store, out),
        ComdType::RPOP => list::rpop(parts, store, out),
        ComdType::LLEN => list::llen(parts, store, out),
        ComdType::LINDEX => list::lindex(parts, store, out),
        ComdType::LSET => list::lset(parts, store, out),
        ComdType::LRANGE => list::lrange(parts, store, out),
        ComdType::LTRIM => list::ltrim(parts, store, out),
        ComdType::LREM => list::lrem(parts, store, out),
        ComdType::LINSERT => list::linsert(parts, store, out),
        ComdType::LPOS => list::lpos(parts, store, out),
        ComdType::LMOVE => list::lmove(parts, store, out),
        ComdType::RPOPLPUSH => list::rpoplpush(parts, store, out),
        ComdType::BLPOP => list::blpop(parts, store, out),
        ComdType::BRPOP => list::brpop(parts, store, out),
        ComdType::BLMOVE => list::blmove(parts, store, out),

        ComdType::SADD => set::sadd(parts, store, out),
        ComdType::SREM => set::srem(parts, store, out),
        ComdType::SISMEMBER => set::sismember(parts, store, out),
        ComdType::SMISMEMBER => set::smismember(parts, store, out),
        ComdType::SMEMBERS => set::smembers(parts, store, out),
        ComdType::SCARD => set::scard(parts, store, out),
        ComdType::SPOP => set::spop(parts, store, out),
        ComdType::SRANDMEMBER => set::srandmember(parts, store, out),
        ComdType::SMOVE => set::smove(parts, store, out),
        ComdType::SUNION => set::sunion(parts, store, out),
        ComdType::SINTER => set::sinter(parts, store, out),
        ComdType::SDIFF => set::sdiff(parts, store, out),
        ComdType::SUNIONSTORE => set::sunionstore(parts, store, out),
        ComdType::SINTERSTORE => set::sinterstore(parts, store, out),
        ComdType::SDIFFSTORE => set::sdiffstore(parts, store, out),
        ComdType::SINTERCARD => set::sintercard(parts, store, out),
        ComdType::SSCAN => set::sscan(parts, store, out),

        ComdType::ZADD => zset::zadd(parts, store, out),
        ComdType::ZREM => zset::zrem(parts, store, out),
        ComdType::ZSCORE => zset::zscore(parts, store, out),
        ComdType::ZMSCORE => zset::zmscore(parts, store, out),
        ComdType::ZRANK => zset::zrank(parts, store, out),
        ComdType::ZREVRANK => zset::zrevrank(parts, store, out),
        ComdType::ZCARD => zset::zcard(parts, store, out),
        ComdType::ZCOUNT => zset::zcount(parts, store, out),
        ComdType::ZLEXCOUNT => zset::zlexcount(parts, store, out),
        ComdType::ZINCRBY => zset::zincrby(parts, store, out),
        ComdType::ZRANGE => zset::zrange(parts, store, out),
        ComdType::ZREVRANGE => zset::zrevrange(parts, store, out),
        ComdType::ZRANGEBYSCORE => zset::zrangebyscore(parts, store, out),
        ComdType::ZREVRANGEBYSCORE => zset::zrevrangebyscore(parts, store, out),
        ComdType::ZRANGEBYLEX => zset::zrangebylex(parts, store, out),
        ComdType::ZRANGESTORE => zset::zrangestore(parts, store, out),
        ComdType::ZPOPMIN => zset::zpopmin(parts, store, out),
        ComdType::ZPOPMAX => zset::zpopmax(parts, store, out),
        ComdType::BZPOPMIN => zset::bzpopmin(parts, store, out),
        ComdType::BZPOPMAX => zset::bzpopmax(parts, store, out),
        ComdType::ZUNION => zset::zunion(parts, store, out),
        ComdType::ZINTER => zset::zinter(parts, store, out),
        ComdType::ZDIFF => zset::zdiff(parts, store, out),
        ComdType::ZUNIONSTORE => zset::zunionstore(parts, store, out),
        ComdType::ZINTERSTORE => zset::zinterstore(parts, store, out),
        ComdType::ZDIFFSTORE => zset::zdiffstore(parts, store, out),
        ComdType::ZRANDMEMBER => zset::zrandmember(parts, store, out),
        ComdType::ZSCAN => zset::zscan(parts, store, out),

        ComdType::SETBIT => bitmap::setbit(parts, store, out),
        ComdType::GETBIT => bitmap::getbit(parts, store, out),
        ComdType::BITCOUNT => bitmap::bitcount(parts, store, out),
        ComdType::BITPOS => bitmap::bitpos(parts, store, out),
        ComdType::BITOP => bitmap::bitop(parts, store, out),
        ComdType::BITFIELD => bitmap::bitfield(parts, store, out),

        ComdType::PFADD => hll::pfadd(parts, store, out),
        ComdType::PFCOUNT => hll::pfcount(parts, store, out),
        ComdType::PFMERGE => hll::pfmerge(parts, store, out),

        ComdType::JSONSET => json::json_set(parts, store, out),
        ComdType::JSONGET => json::json_get(parts, store, out),
        ComdType::JSONDEL => json::json_del(parts, store, out),
        ComdType::JSONFORGET => json::json_forget(parts, store, out),
        ComdType::JSONTYPE => json::json_type(parts, store, out),
        ComdType::JSONNUMINCRBY => json::json_numincrby(parts, store, out),
        ComdType::JSONNUMMULTBY => json::json_nummultby(parts, store, out),
        ComdType::JSONSTRAPPEND => json::json_strappend(parts, store, out),
        ComdType::JSONSTRLEN => json::json_strlen(parts, store, out),
        ComdType::JSONARRAPPEND => json::json_arrappend(parts, store, out),
        ComdType::JSONARRINDEX => json::json_arrindex(parts, store, out),
        ComdType::JSONARRINSERT => json::json_arrinsert(parts, store, out),
        ComdType::JSONARRLEN => json::json_arrlen(parts, store, out),
        ComdType::JSONARRPOP => json::json_arrpop(parts, store, out),
        ComdType::JSONARRTRIM => json::json_arrtrim(parts, store, out),
        ComdType::JSONOBJKEYS => json::json_objkeys(parts, store, out),
        ComdType::JSONOBJLEN => json::json_objlen(parts, store, out),
        ComdType::JSONTOGGLE => json::json_toggle(parts, store, out),
        ComdType::JSONCLEAR => json::json_clear(parts, store, out),
        ComdType::JSONMGET => json::json_mget(parts, store, out),
        ComdType::JSONRESP => json::json_resp(parts, store, out),

        ComdType::GEOADD => geo::geoadd(parts, store, out),
        ComdType::GEOPOS => geo::geopos(parts, store, out),
        ComdType::GEODIST => geo::geodist(parts, store, out),
        ComdType::GEOHASH => geo::geohash(parts, store, out),
        ComdType::GEOSEARCH => geo::geosearch(parts, store, out),
        ComdType::GEOSEARCHSTORE => geo::geosearchstore(parts, store, out),

        ComdType::XADD => stream::xadd(parts, store, out),
        ComdType::XLEN => stream::xlen(parts, store, out),
        ComdType::XRANGE => stream::xrange(parts, store, out),
        ComdType::XREVRANGE => stream::xrevrange(parts, store, out),
        ComdType::XREAD => stream::xread(parts, store, out),
        ComdType::XTRIM => stream::xtrim(parts, store, out),
        ComdType::XDEL => stream::xdel(parts, store, out),
        ComdType::XGROUP => stream::xgroup(parts, store, out),
        ComdType::XACK => stream::xack(parts, store, out),
        ComdType::XINFO => stream::xinfo(parts, store, out),

        ComdType::MULTI => transaction::multi(out),
        ComdType::DISCARD => transaction::discard(out),
        ComdType::WATCH => transaction::watch(parts, out),
        ComdType::UNWATCH => transaction::unwatch(out),

        _ => out.extend_from_slice(b"-ERR unknown command\r\n"),
    }
}

pub mod bitmap;
pub mod connection;
pub mod geo;
pub mod hash;
pub mod hll;
pub mod json;
pub mod keys;
pub mod list;
pub mod scan;
pub mod set;
pub mod stream;
pub mod string;
pub mod transaction;
pub mod zset;
