services:
  node-1:
    image: rana718/fyrodb:latest
    environment:
      FYRODB_CLUSTER_ENABLED: "true"
      FYRODB_BIND: "0.0.0.0"
      FYRODB_PORT: "8000"
      FYRODB_CLUSTER_PORT: "18000"
      FYRODB_ADVERTISE_ADDR: "127.0.0.1"
      FYRODB_CLUSTER_CONFIG_FILE: "/data/fyrodb-nodes.conf"
      FYRODB_RDB_PATH: "/data/fyrodb.rdb"
      FYRODB_MAX_KEYS: "1000000"
      FYRODB_WORKERS: "2"
    ports:
      - "8000:8000"
      - "18000:18000"
    volumes:
      - node-1-data:/data

  node-2:
    image: rana718/fyrodb:latest
    environment:
      FYRODB_CLUSTER_ENABLED: "true"
      FYRODB_BIND: "0.0.0.0"
      FYRODB_PORT: "8000"
      FYRODB_CLUSTER_PORT: "18000"
      FYRODB_ADVERTISE_ADDR: "127.0.0.1"
      FYRODB_CLUSTER_CONFIG_FILE: "/data/fyrodb-nodes.conf"
      FYRODB_RDB_PATH: "/data/fyrodb.rdb"
      FYRODB_MAX_KEYS: "1000000"
      FYRODB_WORKERS: "2"
    ports:
      - "8001:8000"
      - "18001:18000"
    volumes:
      - node-2-data:/data

  node-3:
    image: rana718/fyrodb:latest
    environment:
      FYRODB_CLUSTER_ENABLED: "true"
      FYRODB_BIND: "0.0.0.0"
      FYRODB_PORT: "8000"
      FYRODB_CLUSTER_PORT: "18000"
      FYRODB_ADVERTISE_ADDR: "127.0.0.1"
      FYRODB_CLUSTER_CONFIG_FILE: "/data/fyrodb-nodes.conf"
      FYRODB_RDB_PATH: "/data/fyrodb.rdb"
      FYRODB_MAX_KEYS: "1000000"
      FYRODB_WORKERS: "2"
    ports:
      - "8002:8000"
      - "18002:18000"
    volumes:
      - node-3-data:/data

volumes:
  node-1-data:
  node-2-data:
  node-3-data:
